[package]
name = "datamine-cli"
version = "0.1.0"
description = "Command line interface for datamine-core"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "datamine"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
datamine-core = { path = "../datamine-core" }
datamine-web = { path = "../datamine-web" }
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[lints]
workspace = true
